---
# go-task runner file - rest of config in .taskfiles/**.*.yaml
version: "3"

includes:
  backup:
    taskfile: ".taskfiles/backup"
    dir: "{{.ROOT_DIR}}"
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops
  nix:
    taskfile: ".taskfiles/nix"
    dir: "{{.ROOT_DIR}}"
  bootstrap:
    taskfile: ".taskfiles/bootstrap"
    dir: "{{.ROOT_DIR}}"

tasks:
  default:
    silent: true
    cmds:
      - task -l
