# Reachable systemd start limits for forge's native (non-container) services.
#
# Container services get this from the service factory
# (lib/service-factory.nix), which applies mkStartLimit to every unit it
# generates. This file covers the services that are NOT factory-generated.
#
# WHY THIS EXISTS
#
# systemd only marks a unit `failed` once StartLimitBurst starts land inside
# StartLimitIntervalSec. On the inherited 10s/5 default that requires the
# service to fail in under 2.4s, and is outright impossible once RestartSec
# reaches 5s. Slower failures restart forever while `systemctl is-active`
# still reports `active`. Home Assistant crash-looped 367 times in 43 minutes
# that way on 2026-08-16 and no alert fired. Full arithmetic and incident
# detail in lib/systemd-restart.nix.
#
# This is what makes the existing alerting work, not just hygiene: the 47
# mkSystemdServiceDownAlert call sites match on
# node_systemd_unit_state{state="active"} == 0 held for 2m, which a flapping
# unit never satisfies but a `failed` one satisfies indefinitely.
#
# WHY NOT DefaultStartLimitIntervalSec
#
# A manager-wide default would also widen the window for sshd, dhcpcd,
# systemd-udevd, systemd-journald, systemd-logind, nscd, systemd-timesyncd and
# getty@tty1, which all sit on the same inherited default. systemd keeps that
# window tight on purpose: for those units, giving up permanently is far worse
# than looping. A failed sshd on a headless box means losing the machine. They
# are deliberately absent from the lists below.
#
# MAINTENANCE
#
# These are explicit unit names, so a service removed from the host should be
# removed here too. The assertion at the bottom catches names that no longer
# resolve to a real unit.
{ config, lib, mylib, ... }:

let
  inherit (mylib.systemd-restart) mkStartLimit neverGiveUp;

  # Grouped by the unit's RestartSec, because the reachable window scales with
  # it: interval > (burst - 1) * (failureDuration + RestartSec). Each group
  # gets a window that tolerates a ~60s start attempt before giving up.
  byRestartSec = {
    # RestartSec=100ms (rounded down to 0) -- the systemd default.
    "0" = [
      "actual"
      "alertmanager"
      "gatus"
      "glances-web"
      "grafana"
      "home-assistant"
      "homepage-dashboard"
      "loki"
      "paperless-consumer"
      "paperless-scheduler"
      "paperless-task-queue"
      "paperless-web"
      "phpfpm-grocy"
      "pinchflat"
      "pocket-id"
      "prometheus"
      "prometheus-node-exporter"
      "prometheus-postgres-exporter"
      "promtail"
      "resilio"
      "tautulli"
      "zigbee2mqtt"
    ];
    "5" = [
      "ambit"
      "cooklang-federation"
      "filebrowser-quantum"
      "homelab-mcp"
      "marginalia"
      "miniflux"
      "replog"
      "whiskey-whiskey-whiskey"
      "worldmonitor-api"
      "zwave-js-ui"
    ];
    "10" = [
      "cooklang"
      "lading"
      "schoolhouse"
    ];
    "30" = [
      "beszel-hub"
      "grafana-oncall-plugin-setup"
      "pgweb"
      "syncoid-post-fixup-nas1"
    ];
  };

  # Container units that are NOT generated by mylib.mkContainerService and so
  # do not pick up the factory's start limit. They declare
  # virtualisation.oci-containers.containers directly in their own modules.
  #
  # Folding these into the factory is the better long-term fix -- see the
  # stateless-service factory extension already noted for unpackerr/it-tools --
  # but until they migrate they need the window set here, or they stay in
  # exactly the state this whole module exists to remove.
  containersByRestartSec = {
    "0" = [
      "podman-bgutil-pot"
      "podman-dispatcharr"
      "podman-dispatcharr-celery"
      "podman-emqx"
      "podman-grafana-oncall-celery"
      "podman-grafana-oncall-engine"
      "podman-grafana-oncall-redis"
      "podman-netvisor-daemon"
      "podman-netvisor-server"
      "podman-peanut"
      "podman-plex"
      "podman-scrypted"
      "podman-tracearr"
      "podman-valhalla"
    ];
    "10" = [
      "podman-it-tools"
      "podman-teslamate"
    ];
    "30" = [
      "podman-tdarr"
      # unpackerr's RestartSec=30s only started reaching the real unit once the
      # `.service`-suffixed attribute name was fixed; before that it was
      # applied to a phantom unit and the container ran on the 100ms default.
      "podman-unpackerr"
    ];
  };

  # Units that must keep retrying indefinitely. Every one of these already had
  # infinite restart -- but by accident, because its RestartSec made the
  # default window unreachable. Stating it makes the intent reviewable and
  # survives a future change to RestartSec.
  #
  # cloudflared-forge:        tunnel; fails until the network/edge is reachable
  # hermes-agent:             network-dependent agent
  # hermes-agent-log-relay:   `tail -F` follower of hermes-agent; pointless to
  #                           give up while the agent it mirrors keeps retrying
  # beszel-agent:             monitoring agent; must reconnect after any outage
  keepRetrying = [
    "cloudflared-forge"
    "hermes-agent"
    "hermes-agent-log-relay"
    "beszel-agent"
  ];

  allBounded = lib.zipAttrsWith (_: lib.concatLists) [
    byRestartSec
    containersByRestartSec
  ];

  boundedNames = lib.flatten (lib.attrValues allBounded);

  managed = boundedNames ++ keepRetrying;

  # Units a .timer starts, reduced to the bare name used in the lists above.
  # A timer targets <name>.service unless timerConfig.Unit overrides it.
  timerTriggered = lib.mapAttrsToList
    (
      name: timer:
        lib.removeSuffix ".service" (timer.timerConfig.Unit or "${name}.service")
    )
    config.systemd.timers;

  boundedUnits = lib.concatMapAttrs
    (
      restartSecStr: names:
        lib.genAttrs names (_: {
          unitConfig = mkStartLimit { restartSec = lib.toInt restartSecStr; };
        })
    )
    allBounded;

  unboundedUnits = lib.genAttrs keepRetrying (_: { unitConfig = neverGiveUp; });
in
{
  systemd.services = lib.mkMerge [
    boundedUnits
    unboundedUnits
  ];

  # Catch drift: if a service is removed from the host but left in the lists
  # above, this module would otherwise silently synthesise an inert unit with
  # a [Unit] section and no ExecStart.
  assertions = [
    {
      assertion =
        let
          orphans = lib.filter
            (
              n:
              let
                svc = config.systemd.services.${n} or null;
              in
              svc == null || !((svc.serviceConfig or { }) ? ExecStart || (svc.script or "") != "")
            )
            managed;
        in
        orphans == [ ];
      message =
        let
          orphans = lib.filter
            (
              n:
              let
                svc = config.systemd.services.${n} or null;
              in
              svc == null || !((svc.serviceConfig or { }) ? ExecStart || (svc.script or "") != "")
            )
            managed;
        in
        "hosts/forge/core/systemd-restart-policy.nix lists unit(s) with no ExecStart: "
        + lib.concatStringsSep ", " orphans
        + ". Remove them from the lists, or the module will synthesise inert units.";
    }

    # Reject timer-driven units in the bounded lists.
    #
    # Every window above is derived from RestartSec, on the assumption that
    # Restart= is the only thing starting the unit. A .timer is a second,
    # independent start source, and systemd's rate limiter counts ALL start
    # attempts -- successful runs included. So a timer firing faster than
    # (window / burst) fills the burst on its own and wedges a perfectly
    # healthy unit into `failed` with result 'start-limit-hit'.
    #
    # paperless-ai-reprocess did exactly that: a 1m timer against the 721s
    # window its RestartSec=2m earned it, flapping every ~12 minutes and
    # paging twice per cycle. Note the direction of the trap -- the SLOWER a
    # unit's RestartSec, the WIDER its window, and the more certain a timer is
    # to overrun it. It was fixed by dropping Restart= from the unit, letting
    # the timer be the retry, so a failed run stays `failed` for
    # systemd-unit-failed to catch.
    #
    # Rate-sizing the window instead cannot work in general: when RestartSec
    # exceeds the timer period the failure signal is slower than the healthy
    # one, and no (interval, burst) pair separates them.
    {
      assertion = lib.intersectLists boundedNames timerTriggered == [ ];
      message =
        "hosts/forge/core/systemd-restart-policy.nix bounds unit(s) that a .timer starts: "
        + lib.concatStringsSep ", " (lib.intersectLists boundedNames timerTriggered)
        + ". A timer's starts count against StartLimitBurst, so the window will trip on"
        + " successful runs. Drop Restart= from the unit and let the timer retry, or add"
        + " it to keepRetrying if it must never be limited.";
    }
  ];
}
