---
version: "3"

tasks:
  apply-darwin:
    desc: Build and apply nix-darwin configuration
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - task: build-darwin
        vars:
          host: "{{ .host }}"
      - task: .prompt_to_continue
      - darwin-rebuild switch --flake "{{.ROOT_DIR}}/#{{.host}}"
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which darwin-rebuild
        msg: "darwin-rebuild not found"

  build-darwin:
    desc: Build nix-darwin configuration
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - darwin-rebuild build --flake "{{.ROOT_DIR}}/#{{.host}}"
      - nvd diff /run/current-system result
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which darwin-rebuild
        msg: "darwin-rebuild not found"

  build-nixos:
    desc: Build nixos configuration
    silent: true
    vars:
      ssh_user: ryan
      NIXOS_DOMAIN: "{{.NIXOS_DOMAIN | default \"bjw-s.internal\"}}"
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - nix-shell -p nixos-rebuild --run 'nixos-rebuild build --flake .#{{.host}} --fast --use-remote-sudo --build-host "{{.ssh_user}}@{{.host}}.{{.NIXOS_DOMAIN}}" --target-host "{{.ssh_user}}@{{.host}}.{{.NIXOS_DOMAIN}}"'
    preconditions:
      - sh: which nix
        msg: "nix not found"

  apply-nixos:
    desc: Build and apply nixos configuration
    silent: true
    vars:
      ssh_user: ryan
      NIXOS_DOMAIN: "{{.NIXOS_DOMAIN | default \"bjw-s.internal\"}}"
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - nix-shell -p nixos-rebuild --run 'nixos-rebuild switch --flake .#{{.host}} --fast --use-remote-sudo --build-host "{{.ssh_user}}@{{.host}}.{{.NIXOS_DOMAIN}}" --target-host "{{.ssh_user}}@{{.host}}.{{.NIXOS_DOMAIN}}"'
    preconditions:
      - sh: which nix
        msg: "nix not found"

  test-vm:
    desc: Build and run a NixOS configuration in a QEMU VM for testing
    silent: true
    summary: |
      Builds the VM derivation for the specified NixOS host and runs it.
      This allows safe testing of system-level changes without deploying.
      Args:
        host: NixOS host to test (required)
    requires:
      vars:
        - host
    cmds:
      - echo "🔨 Building VM for {{.host}}..."
      - nix build .#nixosConfigurations.{{.host}}.config.system.build.vm --show-trace
      - echo "🚀 Running VM for {{.host}}. Close the VM window to exit."
      - 'echo "💡 Note: This VM runs in isolation and won''t affect your actual system."'
      - ./result/bin/run-{{.host}}-vm
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: 'echo "{{.host}}" | grep -E "^(luna|rydev|nixos-bootstrap)$"'
        msg: "VM testing only available for NixOS hosts (luna, rydev, nixos-bootstrap)"
      - sh: 'test "{{OS}}" != "darwin"'
        msg: |
          ❌ VM testing is not supported on macOS (Darwin)

          The 'nix-test-vm' command requires QEMU, which has compatibility issues on macOS.
          Please run this command on a Linux host, or use alternative testing methods:
          - Build-only validation for a host: /nix-deploy host=<hostname> --build-only
          - General configuration check: /nix-validate

  dns-records:
    desc: Smart diff DNS records - shows only what needs to be added/removed
    silent: true
    summary: |
      Compares generated Caddy records against current BIND zone file.
      Shows only the delta (additions and stale records).

      Usage:
        task nix:dns-records

      The script will:
        1. Generate records from all Caddy virtual hosts
        2. Decrypt and parse current BIND zone file
        3. Show only records that need to be ADDED
        4. Provide step-by-step instructions for updating
    cmds:
      - .taskfiles/nix/scripts/dns-diff.sh
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which sops
        msg: "sops not found - needed to decrypt zone file"

  .prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?
