# hosts/forge/services/alerta.nix
#
# Host-specific configuration for the Alerta service on 'forge'.
# Alerta provides alert consolidation, correlation, and deduplication
# for alerts from Alertmanager, providing a unified view of infrastructure health.
#
# Features:
# - Native OIDC authentication via PocketID (no Caddy auth layer needed)
# - PostgreSQL database backend (auto-provisioned)
# - Integration with Alertmanager via webhook receiver
# - ZFS dataset with Sanoid replication to NAS
# - Backup integration via preseed (disaster recovery)
#
# After deployment, configure PocketID OAuth client:
# 1. Create OAuth client in PocketID admin console
# 2. Client ID: alerta
# 3. Redirect URIs: https://alerta.holthome.net/ (trailing slash required!)
#    Note: Alerta WebUI uses the root URL as callback, not /auth/oidc/callback
# 4. Scopes: openid, profile, email
# 5. Store client secret in sops secrets at: alerta/oidc_client_secret
#
{ config, lib, ... }:

let
  inherit (config.networking) domain;
  forgeDefaults = import ../lib/defaults.nix { inherit config lib; };

  # Service enable check for guard pattern
  serviceEnabled = config.modules.services.alerta.enable or false;

  # PocketID OIDC endpoints
  pocketIdIssuer = "https://id.${domain}";
in
{
  config = lib.mkMerge [
    # Database provisioning (only when alerta is enabled)
    (lib.mkIf serviceEnabled {
      # Declare database requirements for Alerta
      modules.services.postgresql.databases.alerta = {
        owner = "alerta";
        ownerPasswordFile = config.sops.secrets."postgresql/alerta_password".path;
        extensions = [ ]; # Alerta doesn't require special extensions
        permissionsPolicy = "owner-only"; # Alerta only needs its own user to access
      };
    })

    # Alerta service configuration
    {
      modules.services.alerta = {
        enable = true;
        port = 5000;
        listenAddress = "127.0.0.1";

        # CORS - allow access from the Alerta hostname
        corsOrigins = [
          "https://alerta.${domain}"
        ];

        # PostgreSQL database configuration
        database = {
          host = "127.0.0.1";
          port = 5432;
          name = "alerta";
          user = "alerta";
          # Note: passwordFile no longer needed - password is passed via environmentFile
        };

        # Environment file containing PGPASSWORD and OAUTH2_CLIENT_SECRET
        # Generated by SOPS template in secrets.nix
        environmentFile = config.sops.templates."alerta-env".path;

        # Native OIDC authentication via PocketID
        # Note: Requires OAuth client to be created in PocketID admin console
        oidc = {
          enable = true;
          issuerUrl = pocketIdIssuer;
          clientId = "alerta";
          # Note: clientSecretFile no longer needed - secret is passed via environmentFile
          authUrl = "${pocketIdIssuer}/authorize";
          tokenUrl = "${pocketIdIssuer}/api/oidc/token";
          userinfoUrl = "${pocketIdIssuer}/api/oidc/userinfo";
          logoutUrl = "${pocketIdIssuer}/logout";
        };

        # Alertmanager integration - Alerta will query Alertmanager for status sync
        alertmanager.apiUrl = "http://127.0.0.1:9093";

        # Admin users (list of email addresses that always have admin privileges)
        adminUsers = [ "ryan@ryanholt.net" ];

        # Reverse proxy configuration for external access
        # The module uses native Caddy config for custom SPA+API serving
        # No Caddy auth needed - Alerta handles OIDC internally
        reverseProxy = {
          enable = true;
          hostName = "alerta.${domain}";
        };

        # Enable backups
        backup = forgeDefaults.backup;

        # Enable self-healing restore
        preseed = forgeDefaults.mkPreseed [ "syncoid" "local" ];

        # Additional Alerta configuration
        extraConfig = ''
          # Default environment for alerts
          DEFAULT_ENVIRONMENT = 'Production'

          # Alert severity levels (aligned with Alertmanager + Alerta requirements)
          # Must include 'normal' for DEFAULT_NORMAL_SEVERITY
          # Must include 'indeterminate' for DEFAULT_PREVIOUS_SEVERITY
          SEVERITY_MAP = {
            'critical': 1,
            'high': 2,
            'warning': 3,
            'minor': 4,
            'informational': 5,
            'indeterminate': 6,
            'normal': 7,
            'debug': 8,
            'ok': 9,
            'unknown': 10
          }

          # Set default severities to match our severity map
          DEFAULT_NORMAL_SEVERITY = 'normal'
          DEFAULT_PREVIOUS_SEVERITY = 'indeterminate'

          # Auto-close alerts after 24 hours
          AUTO_CLOSE_TIMEOUT = 86400

          # Heartbeat alerts - services should send heartbeats
          HEARTBEAT_TIMEOUT = 300
        '';
      };
    }

    # Infrastructure contributions (guarded by service enable)
    (lib.mkIf serviceEnabled {
      # ZFS snapshot and replication configuration
      modules.backup.sanoid.datasets."tank/services/alerta" = forgeDefaults.mkSanoidDataset "alerta";

      # Service availability alert (native systemd service, not container)
      modules.alerting.rules."alerta-service-down" =
        forgeDefaults.mkSystemdServiceDownAlert "alerta" "Alerta" "alert consolidation";

      # Homepage dashboard contribution
      modules.services.homepage.contributions.alerta = {
        group = "Monitoring";
        name = "Alerta";
        icon = "alerta";
        href = "https://alerta.${domain}";
        description = "Alert Console";
        siteMonitor = "http://127.0.0.1:5000";
        # No widget - Alerta doesn't have a Homepage widget
      };

      # Gatus health check contribution
      modules.services.gatus.contributions.alerta = {
        name = "Alerta";
        group = "Monitoring";
        url = "https://alerta.${domain}";
        interval = "60s";
        conditions = [
          "[STATUS] == 200"
        ];
      };
    })
  ];
}
