# hosts/forge/services/grafana-oncall.nix
#
# Host-specific configuration for Grafana OnCall on 'forge'.
# Grafana OnCall is an incident response and on-call management platform.
#
# Architecture:
# - Engine: Main API server (port 8093)
# - Celery: Background task worker (beat enabled)
# - Redis: Message broker (bundled, port 6379 internal only)
# - Database: SQLite (simple deployment, sufficient for homelab)
#
# Integration:
# - Authenticates through Grafana (OIDC-protected)
# - Grafana plugin connects to OnCall API
# - Alerts route through existing Alertmanager → OnCall

{ config, lib, ... }:
let
  forgeDefaults = import ../lib/defaults.nix { inherit config lib; };
  inherit (config.networking) domain;
  serviceEnabled = config.modules.services.grafana-oncall.enable or false;
  serviceDomain = "oncall.${domain}";
  dataset = "tank/services/grafana-oncall";
  dataDir = "/var/lib/grafana-oncall";

  # Remove trailing newlines from SOPS placeholders
  clean = lib.strings.removeSuffix "\n";
in
{
  config = lib.mkMerge [
    {
      # SOPS secrets for Grafana OnCall
      sops.secrets."grafana-oncall/secret_key" = {
        sopsFile = ../secrets.sops.yaml;
      };
      sops.secrets."grafana-oncall/metrics_secret" = {
        sopsFile = ../secrets.sops.yaml;
      };

      # Environment file template (combines secrets for container consumption)
      # Includes Grafana admin credentials for plugin authentication
      sops.templates."grafana-oncall-env" = {
        content = ''
          SECRET_KEY=${clean config.sops.placeholder."grafana-oncall/secret_key"}
          MIRAGE_SECRET_KEY=${clean config.sops.placeholder."grafana-oncall/secret_key"}
          PROMETHEUS_EXPORTER_SECRET=${clean config.sops.placeholder."grafana-oncall/metrics_secret"}
          GRAFANA_API_URL=http://host.containers.internal:3000
          GRAFANA_ADMIN_USER=admin
          GRAFANA_ADMIN_PASSWORD=${clean config.sops.placeholder."grafana/admin-password"}
        '';
      };

      modules.services.grafana-oncall = {
        enable = true;
        dataDir = dataDir;
        datasetPath = dataset;

        # Public URL for link generation in notifications
        baseUrl = "https://${serviceDomain}";

        # Grafana API URL - use host.containers.internal for container access
        grafanaApiUrl = "http://host.containers.internal:3000";

        # Environment file with secrets (generated by sops.templates)
        environmentFile = config.sops.templates."grafana-oncall-env".path;

        # Prometheus metrics (for internal monitoring)
        metrics = {
          enable = true;
          port = 8093;
          path = "/metrics/";
          labels = {
            service_type = "incident-response";
            exporter = "grafana-oncall";
            function = "alerting";
          };
        };

        # Reverse proxy with PocketID auth (admin access only)
        reverseProxy = {
          enable = true;
          hostName = serviceDomain;
          backend = {
            host = "127.0.0.1";
            port = 8094; # Module listenPort (engine API)
          };
          caddySecurity = forgeDefaults.caddySecurity.admin;
        };

        # Container resource limits
        resources = {
          memory = "512M";
          memoryReservation = "256M";
          cpus = "1.0";
        };

        # Backup configuration (SQLite + config)
        backup = forgeDefaults.mkBackupWithTags "grafana-oncall" [
          "oncall"
          "incident-response"
          "monitoring"
          "forge"
        ];

        # Disaster recovery preseed (disabled - preseed service not yet implemented)
        # preseed = forgeDefaults.mkPreseed [ "syncoid" "local" ];

        # Enable notifications for service events
        notifications.enable = true;

        # Homepage dashboard integration
        homepage = {
          enable = true;
          name = "Grafana OnCall";
          description = "Incident Response Platform";
          icon = "grafana";
          category = "Monitoring";
        };

        # Gatus black-box monitoring
        gatus.enable = true;
      };
    }

    (lib.mkIf serviceEnabled {
      # ZFS dataset replication to NAS
      modules.backup.sanoid.datasets.${dataset} = forgeDefaults.mkSanoidDataset "grafana-oncall";

      # Service availability alert (engine container)
      modules.alerting.rules."grafana-oncall-service-down" =
        forgeDefaults.mkServiceDownAlert "grafana-oncall-engine" "GrafanaOnCall" "incident response platform";

      # Celery worker availability alert
      modules.alerting.rules."grafana-oncall-celery-down" =
        forgeDefaults.mkServiceDownAlert "grafana-oncall-celery" "GrafanaOnCallCelery" "background task worker";

      # Redis availability alert
      modules.alerting.rules."grafana-oncall-redis-down" =
        forgeDefaults.mkServiceDownAlert "grafana-oncall-redis" "GrafanaOnCallRedis" "message broker";

      # Cloudflare tunnel for external access
      modules.services.caddy.virtualHosts.grafana-oncall.cloudflare = {
        enable = true;
        tunnel = "forge";
      };
    })
  ];
}
