{ lib }:

let
  endpointType = lib.types.submodule {
    options = {
      scheme = lib.mkOption {
        type = lib.types.enum [ "http" "https" ];
        default = "http";
        description = "Endpoint protocol.";
      };

      host = lib.mkOption {
        type = lib.types.str;
        default = "127.0.0.1";
        description = "Endpoint host.";
      };

      port = lib.mkOption {
        type = lib.types.port;
        description = "Endpoint port.";
      };
    };
  };

  runtimeType = lib.types.submodule {
    options = {
      kind = lib.mkOption {
        type = lib.types.enum [ "nixos-module" "upstream-module" "custom-systemd" "oci" ];
        description = "Runtime implementation kind.";
      };

      units = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = "Systemd units owned by the runtime adapter.";
      };

      endpoints = lib.mkOption {
        type = lib.types.attrsOf endpointType;
        default = { };
        description = "Named network endpoints published by the runtime adapter.";
      };

      identity = lib.mkOption {
        type = lib.types.submodule {
          options = {
            user = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Runtime user.";
            };

            group = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Runtime group.";
            };
          };
        };
        default = { };
        description = "Runtime process identity.";
      };

      statePaths = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = "Persistent state paths owned by the service.";
      };
    };
  };
in
{
  mkBaseOptions = { description }:
    {
      enable = lib.mkEnableOption description;

      _runtime = lib.mkOption {
        type = lib.types.nullOr runtimeType;
        default = null;
        internal = true;
        description = "Runtime facts generated by the service implementation.";
      };
    };

  mkWebOptions =
    { defaultPort
    , portDescription
    , reverseProxyDescription
    , sharedTypes
    }:
    {
      port = lib.mkOption {
        type = lib.types.port;
        default = defaultPort;
        description = portDescription;
      };

      reverseProxy = lib.mkOption {
        type = lib.types.nullOr sharedTypes.reverseProxySubmodule;
        default = null;
        description = reverseProxyDescription;
      };
    };

  mkStatefulOptions =
    { backupDefault
    , backupDescription
    , dataDirDescription
    , defaultDataDir
    , sharedTypes
    }:
    {
      dataDir = lib.mkOption {
        type = lib.types.path;
        default = defaultDataDir;
        description = dataDirDescription;
      };

      backup = lib.mkOption {
        type = lib.types.nullOr sharedTypes.backupSubmodule;
        default = backupDefault;
        description = backupDescription;
      };
    };
}
