{
  ...
}:
{
  imports = [
    ./adguardhome
    ./attic.nix
    ./attic-admin.nix
    ./bind
    ./blocky
    ./caddy
    ./cfdyndns
    ./chrony
    ./cloudflared
    ./coachiq
    ./dispatcharr
    ./dnsdist
    ./glances
    ./haproxy
    ./nginx
    ./node-exporter
    ./onepassword-connect
    ./openssh
    ./omada
    ./podman
    ./postgresql          # Options only (config generation removed - was causing circular deps with nested databases)
    ./sonarr
    ./unifi
  ];
}
