# modules/nixos/services/copilot-api/default.nix
#
# copilot-api — exposes a GitHub Copilot subscription as an Anthropic
# (/v1/messages) and OpenAI (/v1/chat/completions, /v1/responses,
# /v1/embeddings) compatible HTTP API, so tools that speak either protocol
# (Claude Code, LiteLLM, Open WebUI, hermes-agent) can use Copilot's model
# catalogue without a per-provider API key.
#
# Upstream: https://github.com/caozhiyuan/copilot-api (the maintained fork
# of ericc-ch/copilot-api; npm package @jeffreycao/copilot-api). Multi-arch
# image at ghcr.io/caozhiyuan/copilot-api.
#
# Factory-based implementation (see lib/service-factory.nix, ADR-011).
#
# What the container needs from us
# --------------------------------
# * A persistent app directory (COPILOT_API_HOME=/data) holding:
#     github_token   — the OAuth token minted by GitHub's device-code flow.
#                      NOT a PAT; only `auth login --provider copilot` can
#                      create it, and that flow is interactive (consola
#                      prompt + browser). See "Bootstrap" below.
#     config.json    — auth.apiKeys (client keys), adminApiKey (auto-
#                      generated by the app), providers, modelMappings.
#   Both are 0600 and written by the app itself; they live on the service
#   dataset so they are snapshotted and backed up like any other state.
# * Client API keys. The app has no auth unless auth.apiKeys is non-empty,
#   and once it is, every non-admin route (including /v1/*) requires
#   `Authorization: Bearer <key>` or `x-api-key: <key>`. This module ALWAYS
#   configures at least one key: either the lines of `apiKeysFile` (a sops
#   secret, one key per line) or, when that is null, a key it generates
#   once and keeps at `<dataDir>/api-key` (root:root 0600). The
#   `copilot-api-keys` oneshot merges them into config.json before every
#   start, preserving whatever else the app has written there — and runs
#   even while the main unit is waiting for its GitHub login, so consumers
#   (LiteLLM's `extraCredentialFiles`) can always read the key.
#
# Exposure
# --------
# The container publishes on 127.0.0.1 only (the factory default binds all
# interfaces; forced to loopback below). LAN clients go through Caddy at
# `reverseProxy.hostName`, which stays LAN-only because forge's Caddy binds
# only private addresses and this vhost is never added to the Cloudflare
# tunnel. No caddySecurity: every caller is a machine (Claude Code, LiteLLM),
# the app enforces its own bearer-key auth on every inference route, and a
# PocketID redirect would only break those clients. The two paths the app
# serves unauthenticated (`/` liveness text, `/usage-viewer` static HTML)
# carry no data; the host file additionally 404s `/usage-viewer*` and
# `/admin*` at Caddy so the admin surface is reachable only from forge.
#
# Containers on Podman's default network reach it as
# `http://host.containers.internal:<port>` when `bridgePublishAddress` is
# set to that bridge's host address — that is how LiteLLM consumes it.
# (A shared named network with container DNS was tried first; PostgreSQL
# only listens on, and pg_hba only admits, the default bridge, so moving
# LiteLLM onto another bridge cut it off from its database.)
#
# Bootstrap (one-time, interactive)
# ---------------------------------
# The unit carries ConditionFileNotEmpty on the token file, so with no
# token it is skipped cleanly (no crash loop) and the ServiceDown alert
# fires until you log in. Run, on forge:
#
#     sudo copilot-api-login
#
# which starts a throwaway container on the same data directory, prints a
# GitHub URL + one-time code, and writes github_token once you approve it
# in a browser. Then `systemctl start podman-copilot-api`. The client key
# is at `<dataDir>/api-key` unless you provided `apiKeysFile`.
#
# Failure modes
# -------------
# * Token revoked/expired → the app fails at startup (`setupCopilotToken`)
#   and the unit restart-loops until the start limit; re-run the login.
# * GitHub abuse detection: "excessive automated or scripted use of Copilot
#   may trigger GitHub's abuse-detection systems" (upstream README). This
#   is unsupported use of a Copilot subscription; keep clients modest and
#   keep a second inference route (LiteLLM has one) for when it is
#   rate-limited or down.
{ lib
, mylib
, pkgs
, config
, podmanLib
, ...
}:

let
  serviceName = "copilot-api";
  serviceIds = mylib.serviceUids.${serviceName};
  cfgRef = config.modules.services.${serviceName};
  containerPort = 4141;
  backend = config.virtualisation.oci-containers.backend;
  mainServiceName = "${backend}-${serviceName}";
  mainServiceUnit = "${mainServiceName}.service";
  keysUnitName = "${serviceName}-keys";

  # Inside the container everything lives under /data (COPILOT_API_HOME).
  # On the host that is <dataDir>/data so <dataDir> itself can also hold the
  # root-only api-key file without exposing it to the container.
  appDirIn = "/data";
  appDirOn = cfg: "${cfg.dataDir}/data";
  tokenFileOn = cfg: "${appDirOn cfg}/github_token";
  configFileOn = cfg: "${appDirOn cfg}/config.json";
  generatedKeyFile = cfg: "${cfg.dataDir}/api-key";

  # One-shot device-code login. Bypasses the image entrypoint (which only
  # knows `--auth` → bare `auth`, a parent command that prints usage) and
  # runs the real subcommand with the same uid/volume the service uses, so
  # the resulting github_token is owned correctly and picked up unchanged.
  loginScript = pkgs.writeShellApplication {
    name = "copilot-api-login";
    runtimeInputs = [ pkgs.podman pkgs.coreutils ];
    text = ''
      if [ "$(id -u)" -ne 0 ]; then
        echo "copilot-api-login must run as root (sudo): it needs podman's root storage" >&2
        exit 1
      fi
      install -d -o ${toString serviceIds.uid} -g ${toString serviceIds.gid} -m 0700 "${appDirOn cfgRef}"
      echo "Starting the GitHub device-code login. Approve the code in a browser when prompted."
      exec podman run --rm -it \
        --name copilot-api-login \
        --user ${toString serviceIds.uid}:${toString serviceIds.gid} \
        --entrypoint bun \
        --workdir /app \
        -e HOME=${appDirIn} \
        -e COPILOT_API_HOME=${appDirIn} \
        -v "${appDirOn cfgRef}:${appDirIn}:rw" \
        "${cfgRef.image}" \
        --use-system-ca run dist/main.js auth login --provider copilot
    '';
  };
in
mylib.mkContainerService {
  inherit lib mylib pkgs config podmanLib;

  name = serviceName;
  description = "copilot-api GitHub Copilot inference proxy";

  spec = {
    port = containerPort;
    inherit containerPort;
    image = "ghcr.io/caozhiyuan/copilot-api:v2.3.16@sha256:b85f6e13517513e847ea77efcb098cc9a368e6b5898c3fd129eafbb3eef7237d";
    operationalProfile = "ai";
    displayName = "Copilot API";
    function = "llm_inference_proxy";
    webUI = false;

    # `GET /` answers "Server running" without auth; the alpine/bun image
    # has busybox wget but no curl (factory default check uses curl).
    healthCommand = "wget -q --spider http://127.0.0.1:${toString containerPort}/ || exit 1";
    startPeriod = "60s";

    # A handful of small JSON/token files.
    zfsRecordSize = "16K";

    resources = {
      memory = "512M";
      memoryReservation = "128M";
      cpus = "1.0";
    };

    # The image has no USER directive, but nothing in it needs root: the
    # factory's --user=<uid>:<gid> plus COPILOT_API_HOME=/data is enough.
    runAsRoot = false;

    # State is the /data app dir, mounted from <dataDir>/data (see volumes).
    skipDefaultConfigMount = true;
    volumes = cfg: [ "${appDirOn cfg}:${appDirIn}:rw" ];

    environment = { ... }: {
      HOME = appDirIn;
      COPILOT_API_HOME = appDirIn;
      NODE_ENV = "production";
    };
  };

  extraOptions = {
    apiKeysFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        File containing the client API keys to accept, one per line
        (typically a sops secret). Merged into config.json `auth.apiKeys`
        before every start. When null, a single key is generated on first
        start and kept at <dataDir>/api-key (root:root 0600).
      '';
      example = "/run/secrets/copilot-api/api-keys";
    };

    bridgePublishAddress = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        Additional host address to publish the port on, for containers on
        Podman's default network that reach the host as
        host.containers.internal (10.88.0.1 on forge). Loopback is always
        published. Leave null if nothing in a container needs it.
      '';
      example = "10.88.0.1";
    };

    # copilot-api has no /metrics endpoint; keep the factory default off.
    metrics = lib.mkOption {
      type = lib.types.nullOr mylib.types.metricsSubmodule;
      default = null;
      description = "Prometheus metrics collection (copilot-api exposes none)";
    };
  };

  extraConfig = cfg:
    let
      gid = toString config.users.groups.${cfg.group}.gid;
      keysScript = ''
        set -euo pipefail
        install -d -o ${cfg.user} -g ${gid} -m 0700 "${appDirOn cfg}"

        # --- client API keys ------------------------------------------------
        ${if cfg.apiKeysFile != null then ''
          keys=$(${pkgs.gnugrep}/bin/grep -v '^[[:space:]]*$' "$CREDENTIALS_DIRECTORY/api-keys" || true)
          if [ -z "$keys" ]; then
            echo "copilot-api: apiKeysFile ${cfg.apiKeysFile} contains no keys" >&2
            exit 1
          fi
        '' else ''
          keyfile="${generatedKeyFile cfg}"
          if [ ! -s "$keyfile" ]; then
            umask 077
            printf 'cpk_%s\n' "$(${pkgs.coreutils}/bin/head -c 48 /dev/urandom | ${pkgs.coreutils}/bin/base64 | ${pkgs.coreutils}/bin/tr -d '/+=\n' | ${pkgs.coreutils}/bin/head -c 48)" > "$keyfile"
            echo "copilot-api: generated client API key at $keyfile"
          fi
          keys=$(cat "$keyfile")
        ''}

        # --- merge keys into config.json, preserving everything else --------
        cfgfile="${configFileOn cfg}"
        if [ -s "$cfgfile" ]; then
          existing=$(cat "$cfgfile")
        else
          existing='{}'
        fi
        keys_json=$(printf '%s\n' "$keys" | ${pkgs.jq}/bin/jq -R -s 'split("\n") | map(select(length > 0))')
        printf '%s' "$existing" \
          | ${pkgs.jq}/bin/jq --argjson keys "$keys_json" '.auth = ((.auth // {}) + { apiKeys: $keys })' \
          > "$cfgfile.tmp"
        install -o ${cfg.user} -g ${gid} -m 0600 "$cfgfile.tmp" "$cfgfile"
        rm -f "$cfgfile.tmp"
      '';
    in
    {
      environment.systemPackages = [ loginScript ];

      virtualisation.oci-containers.containers.${serviceName} = {
        # Loopback only. The factory default publishes on all interfaces,
        # which for a service whose only auth is a bearer key would hand the
        # Copilot subscription to anything on the LAN that guessed the key.
        ports = lib.mkForce (
          [ "127.0.0.1:${toString cfg.port}:${toString containerPort}" ]
          ++ lib.optional (cfg.bridgePublishAddress != null)
            "${cfg.bridgePublishAddress}:${toString cfg.port}:${toString containerPort}"
        );
      };

      systemd.services.${mainServiceName} = {
        # Skip (not fail) until the one-time device login has produced a
        # token — see "Bootstrap" in the header. The app would otherwise
        # open an interactive provider-selection prompt with no TTY and
        # crash-loop.
        unitConfig.ConditionFileNotEmpty = tokenFileOn cfg;
        after = [ "${keysUnitName}.service" ];
        requires = [ "${keysUnitName}.service" ];
      };

      # Client-key provisioning. Deliberately its own unit so it runs (and
      # the generated key exists for LiteLLM to read) even while the main
      # unit is skipped waiting for the GitHub login.
      systemd.services.${keysUnitName} = {
        description = "copilot-api client API key provisioning";
        wantedBy = [ "multi-user.target" ];
        before = [ mainServiceUnit ];
        requiredBy = [ mainServiceUnit ];
        partOf = [ mainServiceUnit ];
        # Must not run before the dataset is mounted (and, on a rebuild,
        # restored): on 2026-09-04 this unit fired at multi-user.target ahead
        # of zfs-service-datasets, created <dataDir>/data on the root
        # filesystem, and the dataset was never created underneath it.
        after = [ "zfs-service-datasets.service" "preseed-${serviceName}.service" ];
        requires = [ "zfs-service-datasets.service" ];

        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          LoadCredential =
            lib.optional (cfg.apiKeysFile != null) "api-keys:${cfg.apiKeysFile}";
        };

        script = keysScript;
        # Re-run on the next switch whenever the assembled script changes
        # (RemainAfterExit oneshots are otherwise left as-is, issue #852).
        restartTriggers = [ keysScript ];
      };
    };
}
