---
ignore: |
  .direnv/
  .private/
  .vscode/
  **/*.sops.yaml

extends: default

rules:
  truthy:
    allowed-values: ["true", "false", "on"]

  comments:
    min-spaces-from-content: 1

  line-length: disable

  # GitHub workflows and config files commonly omit document-start
  document-start: disable
