# Common monitoring hub configuration
#
# This profile defines the "monitoring hub" role for a host. It sets up
# the central Prometheus server and Alertmanager.
#
# To use it, import this file into a host's configuration and then specify
# the `services.prometheus.scrapeConfigs` for that instance.
{ config, ... }:

{
  # The alerting module is an integral part of the monitoring hub.
  # This enables Alertmanager and wires up its configuration.
  modules.alerting.enable = true;

  # Central Prometheus SERVER configuration.
  services.prometheus = {
    enable = true;

    # Prometheus listens on localhost only (not exposed externally via this service).
    listenAddress = "127.0.0.1";
    port = 9090;

    # Global scrape/evaluation cadence.
    globalConfig = {
      scrape_interval = "15s";
      evaluation_interval = "15s";
      external_labels = {
        # Label metrics with the hostname of the monitoring server itself.
        instance = config.networking.hostName;
        environment = "homelab";
      };
    };

    # Import alert rules generated by the alerting module.
    # This maintains separation: monitoring handles Prometheus, alerting handles Alertmanager.
    ruleFiles = config.modules.alerting.export.ruleFiles;
  };
}
