# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit
, fetchurl
, fetchFromGitHub
, dockerTools
,
}:
{
  beads = {
    pname = "beads";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "steveyegge";
      repo = "beads";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-K3X67XgUl55mZS4r4V/KTbXPNqCV7fPHi8HnrDime+E=";
    };
  };
  cooklang-cli = {
    pname = "cooklang-cli";
    version = "v0.29.1";
    src = fetchFromGitHub {
      owner = "cooklang";
      repo = "CookCLI";
      rev = "v0.29.1";
      fetchSubmodules = false;
      sha256 = "sha256-fg8qq4j9NbQvnduPRBwqp+GyQaHx2axqH39KeMZqy2k=";
    };
  };
  cooklang-federation = {
    pname = "cooklang-federation";
    version = "d4131c0b99ea6cf49db4ab0bd0be3c1b03a3a43e";
    src = fetchFromGitHub {
      owner = "cooklang";
      repo = "federation";
      rev = "d4131c0b99ea6cf49db4ab0bd0be3c1b03a3a43e";
      fetchSubmodules = false;
      sha256 = "sha256-VJIse86XOfHaSJzroA2gY0+yGL4g8atT8PIFpvuZ2/I=";
    };
    date = "2026-04-13";
  };
  shcopy = {
    pname = "shcopy";
    version = "v0.1.5";
    src = fetchFromGitHub {
      owner = "aymanbagabas";
      repo = "shcopy";
      rev = "v0.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-MKlW8HrkXCYCOeO38F0S4c8mVbsG/VcZ+oGFC70amqQ=";
    };
  };
  thelounge-theme-dracula = {
    pname = "thelounge-theme-dracula";
    version = "4366bdd8d17a35ec9d55e4825ddbbaff1ddc5c5e";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "thelounge";
      rev = "4366bdd8d17a35ec9d55e4825ddbbaff1ddc5c5e";
      fetchSubmodules = false;
      sha256 = "sha256-n/g8FPJC/pScNmTusv84B/CHrnoZ04fAPrNXBVzs82c=";
    };
    date = "2023-09-09";
  };
  thelounge-theme-mininapse = {
    pname = "thelounge-theme-mininapse";
    version = "e4093e5fac4e383a204a6e895698fb9f37682c31";
    src = fetchFromGitHub {
      owner = "MiniDigger";
      repo = "thelounge-theme-mininapse";
      rev = "e4093e5fac4e383a204a6e895698fb9f37682c31";
      fetchSubmodules = false;
      sha256 = "sha256-UIoEhmYaIjugjq2zRqBRCSet0ow1u/fSbZlo+y9kmJ0=";
    };
    date = "2023-08-20";
  };
  usage-cli = {
    pname = "usage-cli";
    version = "v3.3.0";
    src = fetchFromGitHub {
      owner = "jdx";
      repo = "usage";
      rev = "v3.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-L8OQ6GdHoxJROA/lczichG4nNx5UGKxInihel5AaFIc=";
    };
  };
}
