# Kometa Module - Plex Metadata Manager
#
# Kometa (formerly Plex Meta Manager) automates metadata management for Plex
# media libraries, including:
# - Custom collections based on TMDb, IMDb, Trakt, and other sources
# - Poster overlays for resolution, audio codec, ratings, etc.
# - Metadata updates for movies, TV shows, and music
# - Playlist management across multiple libraries
#
# **Architecture**:
# - Runs as scheduled systemd timer (not a long-running daemon)
# - Uses Podman containers for isolation
# - Secrets managed via SOPS with environment variable injection
# - Fully declarative configuration generated from Nix options
#
# **Configuration**:
# - Libraries are configured declaratively with collection and overlay defaults
# - TMDb is required for most functionality
# - Trakt/MdbList are optional but enhance collection capabilities
#
# **References**:
# - Kometa Wiki: https://kometa.wiki/
# - GitHub: https://github.com/Kometa-Team/Kometa
{ lib
, mylib
, pkgs
, config
, ...
}:
let
  # Service UID/GID from centralized registry
  serviceIds = mylib.serviceUids.kometa;

  # Storage helpers via mylib injection (centralized import)
  storageHelpers = mylib.storageHelpers pkgs;
  # Import shared type definitions
  sharedTypes = mylib.types;

  cfg = config.modules.services.kometa;
  notificationsCfg = config.modules.notifications;
  storageCfg = config.modules.storage;
  hasCentralizedNotifications = notificationsCfg.enable or false;
  datasetPath = "${storageCfg.datasets.parentDataset}/kometa";

  # Build replication config for preseed (walks up dataset tree to find inherited config)
  replicationConfig = storageHelpers.mkReplicationConfig { inherit config datasetPath; };

  # =============================================================================
  # Configuration File Generation
  # =============================================================================

  mkLibraryConfig = _: libraryConfig: {
    remove_overlays = libraryConfig.removeOverlays;
  }
  // lib.optionalAttrs (libraryConfig.collectionFiles != [ ]) {
    collection_files = map mkFileReference libraryConfig.collectionFiles;
  }
  // lib.optionalAttrs (libraryConfig.overlayFiles != [ ]) {
    overlay_files = map mkFileReference libraryConfig.overlayFiles;
  }
  // lib.optionalAttrs (libraryConfig.metadataFiles != [ ]) {
    metadata_files = map mkFileReference libraryConfig.metadataFiles;
  }
  // lib.optionalAttrs (libraryConfig.operations != null) {
    operations = mkOperationsConfig libraryConfig.operations;
  };

  mkFileReference = ref: {
    ${ref.type} =
      if ref.type == "file" then ref.path
      else if ref.type == "url" then ref.url
      else ref.name;
  } // lib.optionalAttrs (ref.templateVariables != { }) {
    template_variables = ref.templateVariables;
  };

  mkOperationsConfig = ops: lib.filterAttrs (_: value: value != null)
    {
      mass_genre_update = ops.massGenreUpdate;
      mass_audience_rating_update = ops.massAudienceRatingUpdate;
      mass_critic_rating_update = ops.massCriticRatingUpdate;
      mass_content_rating_update = ops.massContentRatingUpdate;
      mass_originally_available_update = ops.massOriginallyAvailableUpdate;
    } // lib.optionalAttrs ops.splitDuplicates {
    split_duplicates = true;
  } // lib.optionalAttrs ops.radarrAddAll {
    radarr_add_all = true;
  } // lib.optionalAttrs ops.sonarrAddAll {
    sonarr_add_all = true;
  };

  mkSettingsConfig = settings: {
    cache = settings.cache;
    cache_expiration = settings.cacheExpiration;
    asset_folders = settings.assetFolders;
    create_asset_folders = settings.createAssetFolders;
    prioritize_assets = settings.prioritizeAssets;
    dimensional_asset_rename = settings.dimensionalAssetRename;
    download_url_assets = settings.downloadUrlAssets;
    show_missing_season_assets = settings.showMissingSeasonAssets;
    show_missing_episode_assets = settings.showMissingEpisodeAssets;
    sync_mode = settings.syncMode;
    minimum_items = settings.minimumItems;
    default_collection_order = settings.defaultCollectionOrder;
    delete_below_minimum = settings.deleteBelowMinimum;
    delete_not_scheduled = settings.deleteNotScheduled;
    run_again_delay = settings.runAgainDelay;
    missing_only_released = settings.missingOnlyReleased;
    show_unmanaged = settings.showUnmanaged;
    show_unconfigured = settings.showUnconfigured;
    show_filtered = settings.showFiltered;
    show_options = settings.showOptions;
    show_missing = settings.showMissing;
    show_missing_assets = settings.showMissingAssets;
    save_report = settings.saveReport;
    tvdb_language = settings.tvdbLanguage;
    item_refresh_delay = settings.itemRefreshDelay;
    run_order = settings.runOrder;
  } // lib.optionalAttrs (settings.assetDirectory != null) {
    asset_directory = settings.assetDirectory;
  };

  # Generate full config.yml content
  configYaml = pkgs.writeText "kometa-config.yml" ''
    ## Kometa Configuration - Generated by NixOS
    ## Do not edit manually - changes will be overwritten

    # Plex server configuration
    plex:
      url: "<<plexurl>>"
      token: "<<plextoken>>"
      timeout: ${toString cfg.plex.timeout}
      db_cache: ${if cfg.plex.dbCache then "true" else "false"}
      clean_bundles: ${if cfg.plex.cleanBundles then "true" else "false"}
      empty_trash: ${if cfg.plex.emptyTrash then "true" else "false"}
      optimize: ${if cfg.plex.optimize then "true" else "false"}

    # TMDb configuration (required)
    tmdb:
      apikey: "<<tmdbapikey>>"
      language: ${builtins.toJSON cfg.tmdb.language}
      region: ${builtins.toJSON cfg.tmdb.region}
      cache_expiration: ${toString cfg.tmdb.cacheExpiration}

    ${lib.optionalString cfg.trakt.enable ''
    # Trakt configuration
    trakt:
      client_id: "<<traktclientid>>"
      client_secret: "<<traktclientsecret>>"
      pin:
    ''}

    ${lib.optionalString cfg.mdblist.enable ''
    # MdbList configuration
    mdblist:
      apikey: "<<mdblistapikey>>"
      cache_expiration: ${toString cfg.mdblist.cacheExpiration}
    ''}

    ${lib.optionalString cfg.omdb.enable ''
    # OMDb configuration
    omdb:
      apikey: "<<omdbapikey>>"
      cache_expiration: ${toString cfg.omdb.cacheExpiration}
    ''}

    # Library configurations
    libraries: ${builtins.toJSON (lib.mapAttrs mkLibraryConfig cfg.libraries)}

    ${lib.optionalString (cfg.playlistFiles != [ ]) ''
    # Playlist files
    playlist_files: ${builtins.toJSON (map mkFileReference cfg.playlistFiles)}
    ''}

    # Global settings
    settings: ${builtins.toJSON (mkSettingsConfig cfg.settings)}
  '';

  # =============================================================================
  # Submodule Types
  # =============================================================================

  # File reference submodule for collection/overlay/metadata files
  fileReferenceSubmodule = lib.types.submodule {
    options = {
      type = lib.mkOption {
        type = lib.types.enum [ "default" "file" "url" "repo" ];
        description = "Type of file reference";
        example = "default";
      };

      name = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Name of default or repo file";
        example = "imdb";
      };

      path = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Path to local file";
        example = "config/MyCollections.yml";
      };

      url = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "URL to remote file";
      };

      templateVariables = lib.mkOption {
        type = lib.types.attrsOf (lib.types.oneOf [ lib.types.str lib.types.int lib.types.bool ]);
        default = { };
        description = "Template variables to customize defaults";
        example = {
          use_separator = false;
          sep_style = "red";
        };
      };
    };
  };

  # Operations submodule for library-level mass updates
  operationsSubmodule = lib.types.submodule {
    options = {
      massGenreUpdate = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Source for mass genre updates (tmdb, imdb, tvdb, omdb)";
        example = "tmdb";
      };

      massAudienceRatingUpdate = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Source for audience rating updates (mdb_tmdb, mdb_imdb, etc.)";
        example = "mdb_tmdb";
      };

      massCriticRatingUpdate = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Source for critic rating updates";
        example = "mdb_metacritic";
      };

      massContentRatingUpdate = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Source for content rating updates";
        example = "mdb_commonsense";
      };

      massOriginallyAvailableUpdate = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Source for release date updates";
        example = "tmdb";
      };

      splitDuplicates = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Split duplicate items in the library";
      };

      radarrAddAll = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Add all library movies to Radarr";
      };

      sonarrAddAll = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Add all library shows to Sonarr";
      };
    };
  };

  # Library submodule
  librarySubmodule = lib.types.submodule {
    options = {
      removeOverlays = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Set to true to remove all overlays from this library";
      };

      collectionFiles = lib.mkOption {
        type = lib.types.listOf fileReferenceSubmodule;
        default = [ ];
        description = "Collection files to apply to this library";
        example = lib.literalExpression ''
          [
            { type = "default"; name = "basic"; }
            { type = "default"; name = "imdb"; }
          ]
        '';
      };

      overlayFiles = lib.mkOption {
        type = lib.types.listOf fileReferenceSubmodule;
        default = [ ];
        description = "Overlay files to apply to this library";
        example = lib.literalExpression ''
          [
            { type = "default"; name = "ribbon"; }
            { type = "default"; name = "resolution"; templateVariables = { use_edition = false; }; }
          ]
        '';
      };

      metadataFiles = lib.mkOption {
        type = lib.types.listOf fileReferenceSubmodule;
        default = [ ];
        description = "Metadata files to apply to this library";
      };

      operations = lib.mkOption {
        type = lib.types.nullOr operationsSubmodule;
        default = null;
        description = "Library-level operations configuration";
      };
    };
  };

  # Settings submodule
  settingsSubmodule = lib.types.submodule {
    options = {
      cache = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable caching";
      };

      cacheExpiration = lib.mkOption {
        type = lib.types.int;
        default = 60;
        description = "Cache expiration in days";
      };

      assetDirectory = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Directory for custom assets";
      };

      assetFolders = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Look for assets in folders named after items";
      };

      createAssetFolders = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Create asset folders for items without them";
      };

      prioritizeAssets = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Prioritize local assets over online sources";
      };

      dimensionalAssetRename = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Rename assets to include dimensions";
      };

      downloadUrlAssets = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Download assets from URLs";
      };

      showMissingSeasonAssets = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Show warnings for missing season assets";
      };

      showMissingEpisodeAssets = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Show warnings for missing episode assets";
      };

      syncMode = lib.mkOption {
        type = lib.types.enum [ "append" "sync" ];
        default = "append";
        description = "Sync mode for collections (append adds, sync removes)";
      };

      minimumItems = lib.mkOption {
        type = lib.types.int;
        default = 1;
        description = "Minimum items required to create a collection";
      };

      defaultCollectionOrder = lib.mkOption {
        type = lib.types.str;
        default = "release";
        description = "Default collection sort order";
      };

      deleteBelowMinimum = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Delete collections below minimum items";
      };

      deleteNotScheduled = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Delete collections not scheduled to run";
      };

      runAgainDelay = lib.mkOption {
        type = lib.types.int;
        default = 2;
        description = "Delay in minutes before running again";
      };

      missingOnlyReleased = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Only show missing items that are already released";
      };

      showUnmanaged = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show unmanaged collections in logs";
      };

      showUnconfigured = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show unconfigured libraries in logs";
      };

      showFiltered = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Show filtered items in logs";
      };

      showOptions = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show available options in logs";
      };

      showMissing = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show missing items in logs";
      };

      showMissingAssets = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show missing assets in logs";
      };

      saveReport = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Save a report of the run";
      };

      tvdbLanguage = lib.mkOption {
        type = lib.types.str;
        default = "eng";
        description = "Language for TVDb lookups";
      };

      itemRefreshDelay = lib.mkOption {
        type = lib.types.int;
        default = 0;
        description = "Delay in seconds between item refreshes";
      };

      runOrder = lib.mkOption {
        type = lib.types.listOf (lib.types.enum [ "operations" "metadata" "collections" "overlays" ]);
        default = [ "operations" "metadata" "collections" "overlays" ];
        description = "Order in which to run tasks";
      };
    };
  };

in
{
  options.modules.services.kometa = {
    enable = lib.mkEnableOption "kometa";

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/kometa";
      description = "Path to Kometa data directory";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "568";
      description = "User account under which Kometa runs.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "media";
      description = "Group under which Kometa runs.";
    };

    image = lib.mkOption {
      type = lib.types.str;
      default = "kometateam/kometa:v2.1.0@sha256:af441b1eeaa3be6a55820f16102d950d12fa52f3bb791b835a6a768385cd3a30";
      description = "Container image for Kometa";
    };

    schedule = lib.mkOption {
      type = lib.types.str;
      default = "*-*-* 00/4:00:00";
      description = "Systemd timer schedule for Kometa runs (every 4 hours by default)";
    };

    timezone = lib.mkOption {
      type = lib.types.str;
      default = "America/New_York";
      description = "Timezone for the container";
    };

    podmanNetwork = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Name of the Podman network to attach to";
    };

    # =============================================================================
    # Plex Configuration
    # =============================================================================

    plex = {
      url = lib.mkOption {
        type = lib.types.str;
        description = "URL to Plex server";
        example = "http://plex:32400";
      };

      tokenFile = lib.mkOption {
        type = lib.types.path;
        description = "Path to file containing Plex token";
      };

      timeout = lib.mkOption {
        type = lib.types.int;
        default = 60;
        description = "Timeout in seconds for Plex API requests";
      };

      dbCache = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Use database cache";
      };

      cleanBundles = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Clean bundles after run";
      };

      emptyTrash = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Empty trash after run";
      };

      optimize = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Optimize database after run";
      };
    };

    # =============================================================================
    # TMDb Configuration (Required)
    # =============================================================================

    tmdb = {
      apiKeyFile = lib.mkOption {
        type = lib.types.path;
        description = "Path to file containing TMDb API key";
      };

      language = lib.mkOption {
        type = lib.types.str;
        default = "en";
        description = "Language for TMDb lookups";
      };

      region = lib.mkOption {
        type = lib.types.str;
        default = "US";
        description = "Region for TMDb lookups";
      };

      cacheExpiration = lib.mkOption {
        type = lib.types.int;
        default = 60;
        description = "Cache expiration in days";
      };
    };

    # =============================================================================
    # Optional Services
    # =============================================================================

    trakt = {
      enable = lib.mkEnableOption "Trakt integration";

      clientIdFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to file containing Trakt client ID";
      };

      clientSecretFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to file containing Trakt client secret";
      };
    };

    mdblist = {
      enable = lib.mkEnableOption "MdbList integration";

      apiKeyFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to file containing MdbList API key";
      };

      cacheExpiration = lib.mkOption {
        type = lib.types.int;
        default = 60;
        description = "Cache expiration in days";
      };
    };

    omdb = {
      enable = lib.mkEnableOption "OMDb integration";

      apiKeyFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to file containing OMDb API key";
      };

      cacheExpiration = lib.mkOption {
        type = lib.types.int;
        default = 60;
        description = "Cache expiration in days";
      };
    };

    # =============================================================================
    # Libraries Configuration
    # =============================================================================

    libraries = lib.mkOption {
      type = lib.types.attrsOf librarySubmodule;
      default = { };
      description = "Plex libraries to manage (keys must match Plex library names exactly)";
      example = lib.literalExpression ''
        {
          "Movies" = {
            collectionFiles = [
              { type = "default"; name = "basic"; }
              { type = "default"; name = "imdb"; }
            ];
            overlayFiles = [
              { type = "default"; name = "ribbon"; }
            ];
          };
          "TV Shows" = {
            collectionFiles = [
              { type = "default"; name = "basic"; }
            ];
          };
        }
      '';
    };

    playlistFiles = lib.mkOption {
      type = lib.types.listOf fileReferenceSubmodule;
      default = [ ];
      description = "Playlist files to apply across libraries";
    };

    settings = lib.mkOption {
      type = settingsSubmodule;
      default = { };
      description = "Global Kometa settings";
    };

    # =============================================================================
    # Run Options
    # =============================================================================

    runOptions = {
      collections = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Run collection operations";
      };

      overlays = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Run overlay operations";
      };

      operations = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Run library operations";
      };

      metadata = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Run metadata operations";
      };
    };

    # =============================================================================
    # Standard Integrations
    # =============================================================================

    backup = lib.mkOption {
      type = lib.types.nullOr sharedTypes.backupSubmodule;
      default = null;
      description = "Backup configuration";
    };

    notifications = lib.mkOption {
      type = lib.types.nullOr sharedTypes.notificationSubmodule;
      default = null;
      description = "Notification configuration";
    };

    preseed = {
      enable = lib.mkEnableOption "automatic restore before service start";

      repositoryUrl = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "URL to Restic repository";
      };

      passwordFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to Restic repository password file";
      };

      environmentFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to environment file for Restic (e.g., R2 credentials)";
      };

      restoreMethods = lib.mkOption {
        type = lib.types.listOf (lib.types.enum [ "syncoid" "local" "restic" ]);
        default = [ "syncoid" "local" ];
        description = "Ordered list of restore methods to attempt";
      };
    };
  };

  config = lib.mkMerge [
    (lib.mkIf cfg.enable {
      # =============================================================================
      # Storage Configuration
      # =============================================================================

      modules.storage.datasets.services.kometa = {
        mountpoint = cfg.dataDir;
        recordsize = "128K";
        compression = "zstd";
        owner = cfg.user;
        group = cfg.group;
      };

      # =============================================================================
      # System User
      # =============================================================================

      users.users.kometa = {
        uid = serviceIds.uid;
        isSystemUser = true;
        group = cfg.group;
        home = "/var/empty";
        shell = "/run/current-system/sw/bin/nologin";
        description = "Kometa service user";
      };

      # Ensure the media group exists
      users.groups.${cfg.group} = lib.mkDefault { };

      # =============================================================================
      # Systemd Service
      # =============================================================================

      system.build.kometaConfig = configYaml;

      systemd.services.kometa-sync = lib.mkMerge [
        {
          description = "Kometa Plex Metadata Manager Sync";
          wants = [ "network-online.target" ];
          after = [ "network-online.target" "zfs-mount.service" ];
          requires = [ "zfs-mount.service" ];

          path = [ pkgs.podman ];

          serviceConfig = {
            Type = "oneshot";
            # NOTE: Run as root to access SOPS template, then drop privileges in container
            # This matches the pattern used by recyclarr and other containerized services
            User = "root";
            Group = "root";

            # Resource limits
            MemoryMax = "2G";
            CPUQuota = "200%";

            EnvironmentFile =
              let
                templatePath = config.sops.templates."kometa-env".path or null;
              in
              if templatePath != null
              then templatePath
              else throw "Kometa requires sops.templates.kometa-env to be configured in host secrets";

            ExecStart =
              let
                templatePath = config.sops.templates."kometa-env".path or (throw "Kometa requires sops.templates.kometa-env");
                runFlags = lib.concatStringsSep " " (
                  lib.optional (!cfg.runOptions.collections) "--no-collections"
                  ++ lib.optional (!cfg.runOptions.overlays) "--no-overlays"
                  ++ lib.optional (!cfg.runOptions.operations) "--no-operations"
                  ++ lib.optional (!cfg.runOptions.metadata) "--no-metadata"
                );
              in
              pkgs.writeShellScript "kometa-sync.sh" ''
                set -euo pipefail

                ${pkgs.yq-go}/bin/yq eval '.' ${configYaml} >/dev/null

                # Copy generated config to data directory
                cp ${configYaml} ${cfg.dataDir}/config.yml
                chown ${cfg.user}:${toString config.users.groups.${cfg.group}.gid} ${cfg.dataDir}/config.yml

                # Run Kometa container
                ${pkgs.podman}/bin/podman run --rm \
                  --name kometa-sync \
                  --user ${cfg.user}:${toString config.users.groups.${cfg.group}.gid} \
                  --log-driver=journald \
                  ${lib.optionalString (cfg.podmanNetwork != null) "--network=${cfg.podmanNetwork}"} \
                  -v ${cfg.dataDir}:/config:rw \
                  -e TZ=${cfg.timezone} \
                  --env-file ${templatePath} \
                  ${cfg.image} \
                  --run ${runFlags}
              '';

            ExecStopPost = ''
              -${pkgs.podman}/bin/podman rm -f kometa-sync
            '';
          };
        }
        # Add Podman network dependency if configured
        (lib.mkIf (cfg.podmanNetwork != null) {
          requires = [ "podman-network-${cfg.podmanNetwork}.service" ];
          after = [ "podman-network-${cfg.podmanNetwork}.service" ];
        })
        # Add failure notifications
        (lib.mkIf (hasCentralizedNotifications && cfg.notifications != null && cfg.notifications.enable) {
          unitConfig.OnFailure = [ "notify@kometa-failure:%n.service" ];
        })
        # Add preseed dependency
        (lib.mkIf cfg.preseed.enable {
          wants = [ "preseed-kometa.service" ];
          after = [ "preseed-kometa.service" ];
        })
      ];

      # Systemd timer
      systemd.timers.kometa-sync = {
        description = "Kometa Plex Metadata Manager Timer";
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnCalendar = cfg.schedule;
          Persistent = true;
          RandomizedDelaySec = "15m";
        };
      };

      # =============================================================================
      # Notification Template
      # =============================================================================

      modules.notifications.templates = lib.mkIf (hasCentralizedNotifications && cfg.notifications != null && cfg.notifications.enable) {
        "kometa-failure" = {
          enable = lib.mkDefault true;
          priority = lib.mkDefault "high";
          title = lib.mkDefault ''<b><font color="red">✗ Service Failed: Kometa</font></b>'';
          body = lib.mkDefault ''
            <b>Host:</b> ''${hostname}
            <b>Service:</b> <code>''${serviceName}</code>

            The Kometa Plex metadata sync has failed.

            <b>Quick Actions:</b>
            1. Check logs:
               <code>ssh ''${hostname} 'journalctl -u kometa-sync -n 100'</code>
            2. Retry sync:
               <code>ssh ''${hostname} 'systemctl start kometa-sync'</code>
          '';
        };
      };

    })

    # Preseed service
    (lib.mkIf (cfg.enable && cfg.preseed.enable) (
      storageHelpers.mkPreseedService {
        serviceName = "kometa";
        dataset = datasetPath;
        mountpoint = cfg.dataDir;
        mainServiceUnit = "kometa-sync.service";
        replicationCfg = replicationConfig;
        datasetProperties = {
          recordsize = "128K";
          compression = "zstd";
          "com.sun:auto-snapshot" = "true";
        };
        resticRepoUrl = cfg.preseed.repositoryUrl;
        resticPasswordFile = cfg.preseed.passwordFile;
        resticEnvironmentFile = cfg.preseed.environmentFile;
        resticPaths = [ cfg.dataDir ];
        restoreMethods = cfg.preseed.restoreMethods;
        hasCentralizedNotifications = hasCentralizedNotifications;
        owner = cfg.user;
        group = cfg.group;
      }
    ))
  ];
}
